name: ZAP-Test

on:
  push: 
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.7.10
        uses: actions/setup-python@v1
        with: 
          python-version: 3.7.15
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4
      - name: Get working directory
        run: echo $(PWD)
      - name: Build Image
        run: docker build -t vampi_docker:latest .
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 vampi_docker:latest
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:5000/'
